sudo: true
dist: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_1d726809695a_key -iv $encrypted_1d726809695a_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- ./sfdx/install
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:lightning:lint ./force-app/main/default/aura
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdxMerge fabien$ sfdx force:package:install -i 04t9A000000D25z
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- sfdx force:org:delete -u ciorg -p
notifications:
  email: false
  slack:
    secure: vqbs1REK1tg4m89x/tVD6lWOBXWWcyVgnxB8MM0hlCkyVjvXVhqEJhV4zFwvuTaOJITqViIfGlBoLzDLTwgZ2hU21sJxkemn4CXWiR/zPjUXqRmcgre5LcSon8c4EKEmKjqhbWf0uu7yHTee6W5IP+edhRkGBklNromTjszP85RtTV8o0HsRsBYQjeVxgXtB1SvDKEFLeuE5qJkp6M6zbYukL/BAkp0YvK7CuKiteBkgXIEv1xLSuD14p98VQbwD/1gO4aG1eOBQXJ7RyjTKhVP7zCxXV7nfwPiSUqMZnLoUu4tOB50U1zXZ/A/LztJx3HPz6XLXcqqI2gJmdwVNDmLY5j1F42UyYQUSKQk4MKbnBiLRgzDUDyIOqXS4eetnhgqVrGX/AIN6LPJJ2Qw/dUIaKACuVHWflLPsydAnDrqI/P3CucH+qswNeuYUNsSe7MdxbCMSfadClP9dBai0uGkoNWC4tkGHnTbnWkZSDVFoIA3SDS9mLOFsUN7WcGz/E9szUQdY70gm5aFRAaC7SoWt43vfLtIvVccpFBdRhve0sI5VGRLSZJRagvCwHdAL+B1v2YfQoKPtr7lNir/Z5whYHJm35J2ry5dObgfyE+H8bHI55CtPBPMO80OCeBZq6FQOJSqgi72QB9PmS0kEy/mSPbSjk6cY8KzcQ554gps=
